name: Bug Report
description: Report bugs with the plugin here.
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true
